### 注册
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "xiusin",
    "password": "123456"
}


### 获取配置
GET http://localhost:3000/setting/get
Content-Type: application/json

### 配置
POST http://localhost:3000/setting/save
Content-Type: application/json
{"sitename":"zig","domain":"http://layuimini.99php.cn","upload":"png|gif|jpg|jpeg|zip|rar","title":"layuimini 简洁易用后台管理模板","keywords":"","descript":"layuimini，最简洁、清爽、易用的layui后台框架模板。","copyright":"© 2019 layuimini.99php.cn MIT license"}


