### 注册
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "xiusin",
    "password": "123456"
}


### 获取配置
GET http://localhost:3000/setting/get
Content-Type: application/json

### 配置
POST http://localhost:3000/setting/save
Content-Type: application/json
{"sitename":"zig","domain":"http://layuimini.99php.cn","upload":"png|gif|jpg|jpeg|zip|rar","title":"layuimini 简洁易用后台管理模板","keywords":"","descript":"layuimini，最简洁、清爽、易用的layui后台框架模板。","copyright":"© 2019 layuimini.99php.cn MIT license"}


### 文章详情
GET http://localhost:3000/article/get?id=1

### 文章列表
GET http://localhost:3000/article/list?page=2&limit=100


### 文章保存
POST http://localhost:3000/article/save
Content-Type: application/json

{
  "title": "123213213",
  "keyword": "",
  "description": "",
  "file": "",
  "video_url": "",
  "article_type": "article_type_original",
  "comment_switch": "0",
  "recomment_type": "0",
  "view_count": "0",
  "content": "asdasdasd"
}
